export interface valueType {
    firstName: string,
    lastName: string,
    profile: string,
    gender: string,
    mail: any,
    dateOfBirth: any,
    mobileCode: any,
    mobileNumber: any,
    password: any,
    passwordConfirmation: any,
    Age:any,
    AgeError:string,
    firstNameError: string,
    lastNameError: string,
    profileError: string,
    genderError: string,
    mailError: string,
    dateOfBirthError: string,
    mobileCodeError: string,
    mobileNumberError: string,
    passwordError: string,
    passwordConfirmationError: string,
}

export const formValue = {
    "firstName": "",
    "lastName": "",
    "profile": "",
    "gender": "",
    "mail": "",
    "dateOfBirth": "",
    "mobileCode": "+91",
    "mobileNumber": "",
    "password": "",
    "passwordConfirmation": "",
    "Age":18,
    "AgeError":"",
    "firstNameError": "",
    "lastNameError": "",
    "profileError": "",
    "genderError": "",
    "mailError": "",
    "dateOfBirthError": "",
    "mobileCodeError": "",
    "mobileNumberError": "",
    "passwordError": "",
    "passwordConfirmationError": "",
}