export const ICONS = {
  appLogo: require('./logo.png'),
  rightArrow: require('./rightArrow.png'),
  rightArrowInput: require('./rightInputArrow.png'),
  calender: require('./calender.png'),
  leftArrowBlack: require('./leftArrowBlack.png'),
  OtpMessage: require('./OtpMessage.png'),
  passwordLock: require('./lock.png'),
  showEye: require('./showEye.png'),
  hideEye: require('./hideEye.png'),
  verified: require('./verified.png'),
  documentUpload: require('./document_upload.png'),
  Heart: require('./heart.png'),
  edit: require('./edit.png'),
  selfieVerified: require('./selfieVerified.png'),
  bluishCyanVerified: require('./bluishCyanVerified.png'),
  premiumCrown: require('./premiumCrown.png'),
  appBack: require('./appBack.png'),
  Settings: require('./Settings.png'),
  Upgrade: require('./Upgrade.png'),
  ProfileDetails: require('./ProfileDetails.png'),
  Privacy: require('./Privacy.png'),
  Preferences: require('./Preferences.png'),
  Invite: require('./Invite.png'),
  dots: require('./dots.png'),
  smile: require('./smile.png'),
  mic: require('./mic.png'),
  favourite: require('./favourite.png'),
  greenVerify: require('./greenVerify.png'),
  notInterested: require('./notInterested.png'),
  connectNow: require('./connectNow.png'),
  premiumStar: require('./premiumStar.png'),
  matchesStar: require('./matchesStar.png'),
  matchesHeart: require('./matchesHeart.png'),
  searchFilter: require('./searchFilter.png'),
  searchBag: require('./searchBag.png'),
  searchLocation: require('./searchLocation.png'),
  searchReligion: require('./searchReligion.png'),
  searchStar: require('./searchStar.png'),
  navHomeActive: require('./tabHomeActive.png'),
  navHomeInActive: require('./tabHomeInActive.png'),
  navHeartActive: require('./tabHeartActive.png'),
  navHeartInActive: require('./tabHeartInActive.png'),
  navSearchActive: require('./tabSearchActive.png'),
  navSearchInActive: require('./tabSearchInActive.png'),
  navDiscoverActive: require('./tabDiscoverActive.png'),
  navDiscoverInActive: require('./navDiscoverActive.png'),
  navMessageActive: require('./tabMessageActive.png'),
  navMessageInActive: require('./tabMessageInActive.png'),
  activeHeart: require('./activeHeart.png'),
  inActiveHeart: require('./inActiveHeart.png'),
  notificationBell: require('./notificationBell.png'),
  add: require('./add.png'),
  subtract: require('./subtract.png'),
  selfieUnVerified: require('./selfieUnVerified.png'),
  crown: require('./crown.png'),
  unVerify: require('./unVerify.png'),
  notificationCardBell: require('./notificationCardBell.png'),
  notificationCardHeart: require('./notificationCardHeart.png'),
  leftArrowBlack2: require('./leftArrowBlack2.png'),
  // leftArrowWhite: require('./leftArrowWhite.png'),
  chatExit: require('./chatExit.png'),
  chatMessage: require('./chatMessage.png'),
  // accept: require('./accept.png'),
  // sendImage: require('./sendImage.png'),
  editSetting: require('./editSetting.png'),
  profileSetting: require('./Profile.png'),
  termsAndService: require('./termsAndService.png'),
  faq: require('./FaqIcon.png'),
  Password: require('./Password.png'),
  DangerTriangle: require('./Danger Triangle.png'),
  delete: require('./delete.png'),
  // calenderManage: require('./calenderManage.png'),
  email: require('./email.png'),
  call: require('./call.png'),
  // rightArrowBlack2: require('./rightArrowBlack2.png'),
  info: require('./info.png'),
  OtherPreferences: require('./OtherPreferences.png'),
  basicPreferneces: require('./basicPreferneces.png'),
  religiousPreferences: require('./religiousPreferences.png'),
  LocationPreferences: require('./LocationPreferences.png'),
  ProfessionalPreferences: require('./ProfessionalPreferences.png'),
  // cardStamp: require('./cardStamp.png'),
  planDetailsClick: require('./planDetailsClick.png'),
  // CouponCard: require('./CouponCard.png'),
  // preview: require('./preview.png'),
  addDetails: require('./addDetails.png'),
  backArrow: require('./backArrow.png'),
  blueTick: require('./blueverify.png'),
  ranking: require('./ranking.png'),
  editIcon: require('./edit-2.png'),
  maleIcon: require('./maleIcon.png'),
  femaleIcon: require('./femaleIcon.png'),
};
