export const IMAGES = {
  splashBG: require('./splashScreenBG.png'),
  loginHeader: require('./Login.png'),
  registerHeader: require('./Register.png'),
  carouselImage1: require('./carouselImage.png'),
  carouselImage2: require('./carouselImage2.png'),
  carouselImage3: require('./carouselImage3.png'),
  forgotPassword: require('./forgotPassword.png'),
  createPassword: require('./createPassword.png'),
  partnerPrefernce: require('./partnerPrefernce.png'),
  IDVerfication: require('./IDVerfication.png'),
  AImatching: require('./Aibg.png'),
  curve: require('./curve.png'),
  // initialNotification: require('./initialNotification.png'),
  activityLogo: require('./activityLogo.png'),
  //
  profilepicture: require('./profilePic.png'),
  // samplePicture: require('./samplePicture.jpeg'),
  pair1: require('./pair1.png'),
  pair2: require('./pair2.png'),
  pair3: require('./pair3.png'),
  matches1: require('./match1.png'),
  matches2: require('./match2.png'),
  matches3: require('./match3.png'),
  getImage: require('./getImage.png'),
  getInterested: require('./getInterested.png'),
  getVerified: require('./getVerified.png'),
  femalePic: require('./female.jpeg'),
};
